sherpa-ncnn/csrc/wave-reader.cc

A wave file may contain metadata. This PR skips the metadata and reads only the data chunk of a wave file.

Fix reading wav with metadata

---

sherpa-ncnn/csrc/CMakeLists.txt
sherpa-ncnn/csrc/conv-emformer-model.cc
sherpa-ncnn/csrc/conv-emformer-model.h
sherpa-ncnn/csrc/meta-data.cc
sherpa-ncnn/csrc/meta-data.h
sherpa-ncnn/csrc/model.cc
sherpa-ncnn/csrc/model.h

So that we can add metadata to the param file, e.g., the value of chunk length, number of layers, etc.
Note the following pre-trained models have been updated. Please re-download them:
- https://huggingface.co/csukuangfj/sherpa-ncnn-conv-emformer-transducer-2022-12-04
- https://huggingface.co/csukuangfj/sherpa-ncnn-conv-emformer-transducer-2022-12-06

Add MetaData layer

---

.github/scripts/run-test.sh
sherpa-ncnn/csrc/CMakeLists.txt
sherpa-ncnn/csrc/conv-emformer-model.cc
sherpa-ncnn/csrc/conv-emformer-model.h
sherpa-ncnn/csrc/generate-int8-scale-table.cc
sherpa-ncnn/csrc/lstm-model.cc
sherpa-ncnn/csrc/lstm-model.h
sherpa-ncnn/csrc/model.cc
sherpa-ncnn/csrc/model.h

https://github.com/Tencent/ncnn/blob/master/tools/quantize/ncnn2table.cpp
is targeted for computer vision, while this PR is dedicated to ASR.
Usage:
1. When converting models using PNNX, please use 
```bash
pnnx ./foo.pt fp16=0
```
(That is, pass `fp16=0` to `pnnx`)
2.
```bash
./bin/generate-int8-scale-table \
./t-zh/encoder_jit_trace-pnnx.ncnn.param \
./t-zh/encoder_jit_trace-pnnx.ncnn.bin \
./t-zh/decoder_jit_trace-pnnx.ncnn.param \
./t-zh/decoder_jit_trace-pnnx.ncnn.bin \
./t-zh/joiner_jit_trace-pnnx.ncnn.param \
./t-zh/joiner_jit_trace-pnnx.ncnn.bin \
./encoder-scale-table.txt \
./joiner-scale-table.txt \
./wave-filenames.txt
```
where `wave-filenames.txt` contains something like below:
```
/path/to/1.wav
/path/to/2.wav
/path/to/foo.wav
```
You can use as many waves as you like.
3. …

generate int8 scale table

---

.github/workflows/build-wheels.yaml

Some users have difficulties in installing `sherpa-ncnn` with `pip install sherpa-ncnn` since they either don't have `cmake` or they don't have a C++ compiler.
To fix that, we upload pre-built wheels to PyPI.
Currently, the following OS on x86 are supported:
- Linux
- macOS
- Windows
Will add support for arm and aarch64.

Publish pre-built wheels to PyPI

---

sherpa-ncnn/csrc/model.cc

The master branch throws a segfault on error, which is not informative. This PR prints more verbose output on errors.

add verbose output if it's unable to create a model

---

ios-swift/SherpaNcnn/SherpaNcnn.xcodeproj/project.pbxproj

To fix the following error in Release build for simulator:
```
ld: in /Users/fangjun/open-source/sherpa-ncnn/build-ios/sherpa-ncnn.framework/sherpa-ncnn(allocator.cpp.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/fangjun/open-source/sherpa-ncnn/build-ios/sherpa-ncnn.framework/sherpa-ncnn' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Change `No` to `Yes` in the following screenshot:

Fix building for iOS

---

.gitignore
build-ios.sh
ios-swift/SherpaNcnn/SherpaNcnn.xcodeproj/project.pbxproj
toolchains/ios.toolchain.cmake

- Update build-ios.sh generate xcframework
- Update ios.toolchain.cmake to support new architecture
- Update Xcode build setting's Header Search Path and replace framework with xcframework
- Add more exclude patterns in .gitignore

Migrate from framework to xcframework in order to support Apple Silicon

---

sherpa-ncnn/csrc/greedy-search-decoder.cc
sherpa-ncnn/csrc/hypothesis.h
sherpa-ncnn/csrc/modified-beam-search-decoder.cc
sherpa-ncnn/csrc/recognizer.cc
sherpa-ncnn/csrc/recognizer.h
sherpa-ncnn/csrc/sherpa-ncnn.cc

hi, our project need timestamps with sherpa-ncnn, current sherpa-ncnn has no timestamps output,  I have completed this. But also has some confusions:
1. [sherpa-ncnn-alsa.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc) and [sherpa-ncnn-microphone.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc) need to print timestamps result
2. https://github.com/xiangxyq/sherpa-ncnn/blob/cj-add-timestamps/sherpa-ncnn/csrc/recognizer.h#L38 
timestamps use float instead int32, if use Convert like sherpa https://github.com/k2-fsa/sherpa/blob/4756d4ec10c61164eff356190740527993844df3/sherpa/cpp_api/online-stream.h#L17 ,  need extra struct
4. https://github.com/xiangxyq/sherpa-ncnn/blob/28b77f7f6f1820fb0149530b5ef5c933 …

support timestamps

---

python-api-examples/decode-file.py
sherpa-ncnn/python/sherpa_ncnn/recognizer.py

Also, we don't require wave_file.sample_rate == recognizer.sample_rate. If they are different, we will do resampling inside sherpa-ncnn.

Update python example for streaming recognition.

---

cmake/kaldi-native-fbank.cmake
cmake/ncnn.cmake
cmake/portaudio.cmake
cmake/pybind11.cmake

People from China have difficulty downloading cmake dependencies while installing sherpa-ncnn. This commit adds alternative URLs for downloading deps.

Add alternative URLs for cmake dependencies.

---

.github/workflows/linux.yaml
.gitignore
CMakeLists.txt
ffmpeg-examples/CMakeLists.txt
ffmpeg-examples/Makefile
ffmpeg-examples/README.md
ffmpeg-examples/sherpa-ncnn-ffmpeg.cc

By default, ffmpeg-examples is disabled, please enable it by:
cmake -DSHERPA_NCNN_ENABLE_FFMPEG_EXAMPLES=ON ..
You can also use make to build the ffmpeg-examples as before, however, cmake is better because the whole project is cmake, and you can debug in CLion, etc.

Support cmake for ffmpeg-examples.

---

ffmpeg-examples/sherpa-ncnn-ffmpeg.cc
sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc
sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc
sherpa-ncnn/csrc/sherpa-ncnn.cc

Sherpa supports config by CLI, for example:
```bash
./bin/sherpa-ncnn-ffmpeg  \
./models/tokens.txt \
./models/encoder_jit_trace-pnnx.ncnn.param  \
./models/encoder_jit_trace-pnnx.ncnn.bin \
./models/decoder_jit_trace-pnnx.ncnn.param \
./models/decoder_jit_trace-pnnx.ncnn.bin \
./models/joiner_jit_trace-pnnx.ncnn.param  \
./models/joiner_jit_trace-pnnx.ncnn.bin \
rtmp://localhost/live/livestream
```
If start by docker, or k8s, it's better to config by envrionment variables, for example:
```bash
env SHERPA_NCNN_TOKENS=./models/tokens.txt \
SHERPA_NCNN_ENCODER_PARAM=./models/encoder_jit_trace-pnnx.ncnn.param  \
SHERPA_NCNN_ENCODER_BIN=./models/encoder_jit_trace-pnnx.ncnn.bin \
SHERPA_NCNN_DECODER_PARAM=./models/decoder_jit_trace-pnnx.ncnn.param \ …
```

Support config by environment variables.

---

CMakeLists.txt

Support debug in release mode:
```
cmake -DSHERPA_NCNN_ENABLE_DEBUG_FOR_RELEASE=on ..
```
Because debug mode can't work, see #147

Support debug in release mode.

---

ffmpeg-examples/sherpa-ncnn-ffmpeg.cc
sherpa-ncnn/csrc/display.h

The sherpa_ncnn::Display use a window and rewrite the current line, which might not work when another program read the stderr.
If the console width smaller than the sherpa_ncnn::Display window, it causes the text repeat, like this:
```text
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
3: in many languages this standard form came to be considered the
only proper one despite being …
```

Support simple display, without window support.

---

ffmpeg-examples/CMakeLists.txt
ffmpeg-examples/sherpa-ncnn-ffmpeg.cc

If user select incorrect microphone device, or muted it, FFmpeg get all zero samples, and K2 can't work. This PR detects and writes logs to warn user.
Write event logs to stdout to allow user to seperate it from ASR text which write to stderr.
Allow user to send SIGUSR1 about the stream republish event, so we will restart the ASD for new stream.
User can set the env SHERPA_NCNN_DISPLAY_LABEL for the ASR text prefix.

Support ASD(Active speaker detection) for incorrect microphone.

---

ffmpeg-examples/sherpa-ncnn-ffmpeg.cc

If there are SHERPA_NCNN_ASD_SAMPLES seconds of zero samples during SHERPA_NCNN_ASD_ENDPOINTS endpoints, it's no ASD and might be something wrong with microphone.
By default, disabled if SHERPA_NCNN_ASD_SAMPLES or SHERPA_NCNN_ASD_ENDPOINTS is zero.

Support config ASD by env.

---

.github/workflows/test-pip-install.yaml
CMakeLists.txt
cmake/kaldi-native-fbank.cmake
cmake/ncnn.cmake
sherpa-ncnn/csrc/CMakeLists.txt

People are getting the following error on windows when using `pip install sherpa-ncnn`.
```
Traceback (most recent call last):
File ".github/scripts/test-recognizer.py", line 6, in <module>
import sherpa_ncnn
File "C:\hostedtoolcache\windows\Python\3.[8](https://github.com/k2-fsa/sherpa-ncnn/actions/runs/4505931882/jobs/7932189031#step:8:9).[10](https://github.com/k2-fsa/sherpa-ncnn/actions/runs/4505931882/jobs/7932189031#step:8:11)\x64\lib\site-packages\sherpa_ncnn\__init__.py", line 1, in <module>
from .recognizer import Recognizer
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\sherpa_ncnn\recognizer.py", line 4, in <module>
from _sherpa_ncnn import (
ImportError: DLL load failed while importing _sherpa_ncnn: The specified module could not be found.
```
The PR …

Fix installing on windows about the python module

---

sherpa-ncnn/c-api/c-api.cc
sherpa-ncnn/c-api/c-api.h
sherpa-ncnn/csrc/decoder.h
sherpa-ncnn/csrc/greedy-search-decoder.cc
sherpa-ncnn/csrc/modified-beam-search-decoder.cc
sherpa-ncnn/csrc/recognizer.cc
sherpa-ncnn/csrc/recognizer.h
sherpa-ncnn/csrc/stream.cc

Added timestamp for greed search and modified beam search decoder. 
SherpaNcnnResult now includes tokens, timestamps and count besides of existing text field.  Tokens and timestamps are stored in continuous memory in which each token and timestamp ends with nullptr. Use count and pointer increment to get each token and timestamp.
Client can compose words from tokens. For English, the first token of  new word starts with space, while for Chinese, each token is a word.

Added Timetamp

---

.github/workflows/dot-net.yaml
CMakeLists.txt
scripts/dotnet/sherpa-ncnn.cs
scripts/dotnet/sherpa-ncnn.csproj.in
scripts/dotnet/sherpa-ncnn.csproj.runtime.in

Change Marshal.PtrToStringAnsi to Marshal.PtrToStringUTF8 to fix encoding issues on Windows.
Since PtrToStringUTF8 is only available from .netstandard2.1, we upgrade .netstandard2.0 to .netstandard2.1

Fix encoding issues for C#

---

CMakeLists.txt
pack-for-embedded-systems.sh

- Use the master branch from tencent/ncnn
- enable GPU support for zipformer
- enable fp16 support for LSTM and zipformer
- You need to re-export zipformer models to sherpa-ncnn or re-download zipformer models
We have pre-built APKs at
https://huggingface.co/csukuangfj/sherpa-ncnn-apk/tree/main

Release v2.0

---

python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py
python-api-examples/speech-recognition-from-microphone.py

chinese characters can normal show in console, some (not all) window systems, sherpa_ncnn.Display() cannot handle the encoding correctly, while python's print works fine.

fix garbled console output with chinese characters

---

sherpa-ncnn/python/csrc/recognizer.cc
sherpa-ncnn/python/sherpa_ncnn/recognizer.py

Implemented `tokens`, `stokens`, and `timestamps` in Python API. I've tested this on Linux and MacOS and it seems to work.

Implemented tokens, stokens, and timestamps in Python API

---

build-android-x86.sh
build-apk.sh

Fixes #227 
The generated libs should be copied to
```
android/SherpaNcnn/app/src/main/jniLibs/x86/
```

build script for android-x86

---

sherpa-ncnn/csrc/symbol-table.cc

```
/Users/finger/Projects/ClionProjects/sherpa-ncnn/sherpa-ncnn/csrc/symbol-table.cc:50:18: error: expected ';' after expression
std::istrstream is(p, asset_length);
^
;
/Users/finger/Projects/ClionProjects/sherpa-ncnn/sherpa-ncnn/csrc/symbol-table.cc:50:8: error: no member named 'istrstream' in namespace 'std'
std::istrstream is(p, asset_length);
~~~~~^
/Users/finger/Projects/ClionProjects/sherpa-ncnn/sherpa-ncnn/csrc/symbol-table.cc:50:19: error: use of undeclared identifier 'is'
std::istrstream is(p, asset_length);
^
/Users/finger/Projects/ClionProjects/sherpa-ncnn/sherpa-ncnn/csrc/symbol-table.cc:51:8: error: use of undeclared identifier 'is'
Init(is);
^
4 errors generated.
make[2]: *** [sherpa-ncnn/csrc/CMakeFiles/sherpa-ncnn-core.dir/symbol-table.cc.o] Error 1
make[1]: *** …
```

fix build error with ndk

---

CMakeLists.txt
cmake/kaldi-native-fbank.cmake

The file size of the shared library of kaldi-native-fbank is reduced from 161KB to 113KB with this PR.
```
-rwxr-xr-x  1 fangjun  staff   161K Oct 17 15:23 libkaldi-native-fbank-core.dylib
```
```
-rwxr-xr-x  1 fangjun  staff   113K Jan 12 17:27 libkaldi-native-fbank-core.dylib
```

Update kaldi-native-fbank from 1.18.5 to 1.18.6

---

.github/workflows/wasm-simd-hf-space-en.yaml
.github/workflows/wasm-simd-hf-space-zh-en.yaml

We have two huggingface spaces for ASR with WebAssembly
(1) For English only
https://huggingface.co/spaces/k2-fsa/web-assembly-asr-sherpa-ncnn-en
(2) For Chinese + English (Mostly Chinese)
https://huggingface.co/spaces/k2-fsa/web-assembly-asr-sherpa-ncnn-zh-en

Upload wasm files to huggingface spaces
