k2-fsa/sherpa-ncnn

CMakeLists.txt
cmake/ncnn.cmake
sherpa-ncnn/csrc/CMakeLists.txt
sherpa-ncnn/csrc/conv-emformer-model.cc
sherpa-ncnn/csrc/conv-emformer-model.h
sherpa-ncnn/csrc/lstm-model.cc
sherpa-ncnn/csrc/lstm-model.h
sherpa-ncnn/csrc/model.cc
sherpa-ncnn/csrc/model.h

It requires:
- https://github.com/csukuangfj/ncnn/pull/7
- https://github.com/k2-fsa/icefall/pull/717

Support conv-emformer

---

build-aarch64-linux-gnu.sh
build-android-arm64-v8a-with-vulkan.sh
build-arm-linux-gnueabihf.sh

Print informative messages on error.

Small fixes to the cross-compiling scripts

---

build-android-arm64-v8a-with-vulkan.sh
cmake/ncnn.cmake
sherpa-ncnn/csrc/conv-emformer-model.cc
sherpa-ncnn/csrc/conv-emformer-model.h
sherpa-ncnn/csrc/generate-int8-scale-table.cc
sherpa-ncnn/csrc/lstm-model.cc
sherpa-ncnn/csrc/lstm-model.h
sherpa-ncnn/csrc/model.cc
sherpa-ncnn/csrc/model.h
sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc
sherpa-ncnn/csrc/sherpa-ncnn.cc
sherpa-ncnn/jni/jni.cc

It includes optimizations for gemm.
See
- https://github.com/Tencent/ncnn/pull/4387
- https://github.com/Tencent/ncnn/pull/4407
- https://github.com/Tencent/ncnn/pull/4411
- https://github.com/Tencent/ncnn/pull/4414
- https://github.com/Tencent/ncnn/pull/4421
- https://github.com/Tencent/ncnn/pull/4426
- https://github.com/Tencent/ncnn/pull/4430

Use the latest master of ncnn

---

.gitignore
CMakeLists.txt
MANIFEST.in
cmake/cmake_extension.py
cmake/pybind11.cmake
setup.py
sherpa-ncnn/CMakeLists.txt
sherpa-ncnn/python/CMakeLists.txt
sherpa-ncnn/python/csrc/CMakeLists.txt
sherpa-ncnn/python/csrc/decode.cc
sherpa-ncnn/python/csrc/decode.h
sherpa-ncnn/python/csrc/features.cc
sherpa-ncnn/python/csrc/features.h
sherpa-ncnn/python/csrc/mat-util.cc
sherpa-ncnn/python/csrc/mat-util.h
sherpa-ncnn/python/csrc/model.cc
sherpa-ncnn/python/csrc/model.h
sherpa-ncnn/python/csrc/sherpa-ncnn.cc
sherpa-ncnn/python/csrc/sherpa-ncnn.h
sherpa-ncnn/python/sherpa_ncnn/__init__.py
sherpa-ncnn/python/sherpa_ncnn/recognizer.py

```python3
#!/usr/bin/env python3
import wave
import numpy as np
import sherpa_ncnn
def main():
recognizer = sherpa_ncnn.Recognizer(
tokens="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/tokens.txt",
encoder_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/encoder_jit_trace-pnnx.ncnn.param",
encoder_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/encoder_jit_trace-pnnx.ncnn.bin",
decoder_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/decoder_jit_trace-pnnx.ncnn.param",
decoder_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/decoder_jit_trace-pnnx.ncnn.bin",
joiner_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/joiner_jit_trace-pnnx.ncnn.param",
joiner_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/joiner_jit_trace-pnnx.ncnn.bin", …
```

Add Python API

---

python-api-examples/README.md
python-api-examples/decode-file.py
python-api-examples/speech-recognition-from-microphone.py
sherpa-ncnn/python/sherpa_ncnn/recognizer.py

```bash
pip install sherpa-ncnn
```
```python3
#!/usr/bin/env python3
#
import sys
try:
import sounddevice as sd
except ImportError as e:
print("Please install sounddevice first. You can use")
print()
print("  pip install sounddevice")
print()
print("to install it")
sys.exit(-1)
import sherpa_ncnn
def create_recognizer():
recognizer = sherpa_ncnn.Recognizer(
tokens="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/tokens.txt",
encoder_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/encoder_jit_trace-pnnx.ncnn.param",
encoder_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/encoder_jit_trace-pnnx.ncnn.bin",
decoder_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/decoder_jit_trace-pnnx.ncnn.param",
decoder_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/decode …
```

Add Python API examples - Real-time speech recognition with a microphone

---

android/SherpaNcnn/app/src/main/java/com/k2fsa/sherpa/ncnn/MainActivity.kt
android/SherpaNcnn/app/src/main/java/com/k2fsa/sherpa/ncnn/SherpaNcnn.kt
sherpa-ncnn/csrc/endpoint.cc
sherpa-ncnn/csrc/endpoint.h
sherpa-ncnn/csrc/greedy-search-decoder.cc
sherpa-ncnn/csrc/greedy-search-decoder.h
sherpa-ncnn/csrc/model.cc
sherpa-ncnn/csrc/modified-beam-search-decoder.cc
sherpa-ncnn/csrc/modified-beam-search-decoder.h
sherpa-ncnn/csrc/recognizer.cc
sherpa-ncnn/csrc/recognizer.h
sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc
sherpa-ncnn/csrc/sherpa-ncnn.cc
sherpa-ncnn/jni/jni.cc

A pre-built apk can be downloaded from
- hugging face: https://huggingface.co/csukuangfj/sherpa-ncnn-apk/resolve/main/2023-01-06-endpointing-int8-quantization-mixed-english-chinese-sherpa-ncnn.apk
- or 百度网盘:  https://pan.baidu.com/s/1DcEog94g65lDeoZCg25kIw?pwd=cc3s

add endpointing for android

---

cmake/kaldi-native-fbank.cmake

it causes compilation issues for some users on Windows.

disable logs from kaldi-native-fbank

---

sherpa-ncnn/csrc/alsa.cc
sherpa-ncnn/csrc/alsa.h
sherpa-ncnn/csrc/display.h
sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc
sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc
sherpa-ncnn/csrc/sherpa-ncnn.cc

Screen-shot for this PR
We use the same line to display texts belonging to the same segment.

Fix displaying for real-time speech recogntion

---

.github/scripts/swift-api-test.sh
.github/workflows/swift-api-test.yaml
CMakeLists.txt
Info.plist
build-ios.sh
build-swift-macos.sh
sherpa-ncnn/c-api/CMakeLists.txt
sherpa-ncnn/csrc/CMakeLists.txt
sherpa-ncnn/csrc/greedy-search-decoder.cc
sherpa-ncnn/csrc/modified-beam-search-decoder.cc
swift-api-examples/.gitignore
swift-api-examples/SherpaNcnn-Bridging-Header.h
swift-api-examples/SherpaNcnn.swift
swift-api-examples/decode-file.swift
swift-api-examples/run-decode-file.sh
toolchains/ios.toolchain.cmake

This PR also adds APIs for the swift language.
Will update documentation for usage in separate pull-requests.

build sherpa-ncnn as a framework for ios

---

CMakeLists.txt
sherpa-ncnn/csrc/hypothesis.cc
sherpa-ncnn/csrc/hypothesis.h
sherpa-ncnn/csrc/math.h
sherpa-ncnn/csrc/modified-beam-search-decoder.cc
sherpa-ncnn/csrc/modified-beam-search-decoder.h

Closes #97 
Thanks to @kobenaxie  for pointing it out.

Optimize modified_beam_search

---

sherpa-ncnn/csrc/lstm-model.cc
sherpa-ncnn/csrc/lstm-model.h
sherpa-ncnn/csrc/meta-data.h
sherpa-ncnn/csrc/model.cc
sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc
sherpa-ncnn/csrc/sherpa-ncnn.cc

Make the LSTM model options configurable.

Fixes for LSTM models.

---

.github/scripts/run-test.sh

This PR adds test for a small LSTM transducer model.

add test for small lstm transducer model

---

ffmpeg-examples/Makefile
ffmpeg-examples/sherpa-ncnn-ffmpeg.c

Thanks to @begeekmyfriend for his contribution!

Integrate with FFmpeg decode filter audio demo

---

CMakeLists.txt
pack-for-embedded-systems.sh

Release v1.6.0

---

CMakeLists.txt

- bugfixes
- Remove cached feature frames manually

Release v1.7.0

---

ffmpeg-examples/sherpa-ncnn-ffmpeg.cc

1. Global variables changed to static.
2. Prefix with ffmpeg- for FFmpeg variables.
3. Define variable as late as when use them.

Refine code style to follow sherpa-ncnn

---

ffmpeg-examples/README.md
ffmpeg-examples/sherpa-ncnn-ffmpeg.cc

AVFormatContext: https://github.com/k2-fsa/sherpa-ncnn/pull/179/commits/0d1b9e48b05a4ee47e5574e8c6e7510450bcf831
AVCodecContext: https://github.com/k2-fsa/sherpa-ncnn/pull/179/commits/4a6b4e472035aae4c3bb7858686e2a7b0bc09c9b
AVFilterGraph: https://github.com/k2-fsa/sherpa-ncnn/pull/179/commits/c7d7baba0d63713f45e66f256fb98aa52c9758e0
AVFilterInOut: https://github.com/k2-fsa/sherpa-ncnn/pull/179/commits/5a127eefed019f5c5ed8b17bdc1b5da7ef895e3f
AVPacket or AVFrame: https://github.com/k2-fsa/sherpa-ncnn/pull/179/commits/5bd97814ffc2c8bff6378985efd399017a89a953
Unref packet and frame: https://github.com/k2-fsa/sherpa-ncnn/pull/179/commits/2660ee72dcfb3b8d8d648c3457a140969ba86c71

FFmpeg: Manage objects by C++11 smart pointers.

---

ffmpeg-examples/sherpa-ncnn-ffmpeg.cc

According to the comments of FFmepg API:
```
/**
* Allocate an AVCodecContext and set its fields to default values. The
* resulting struct should be freed with avcodec_free_context().
*
* @param codec if non-NULL, allocate private data and initialize defaults
*              for the given codec. It is illegal to then call avcodec_open2()
*              with a different codec.
*              If NULL, then the codec-specific defaults won't be initialized,
*              which may result in suboptimal default settings (this is
*              important mainly for encoders, e.g. libx264).
*
* @return An AVCodecContext filled with default values or NULL on failure.
*/
AVCodecContext *avcodec_alloc_context3(const AVCodec *codec);
```
I note there is a note  `may result in suboptimal default …

FFmpeg: Create decoder context with dec, never use NULL.

---

sherpa-ncnn/csrc/modified-beam-search-decoder.cc

The previous implementation does not use hyp.log_prob when computing top k. This pull-request fixes that.
---
For the following command
```bash
./build/bin/sherpa-ncnn \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/tokens.txt \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/encoder_jit_trace-pnnx.ncnn.param \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/encoder_jit_trace-pnnx.ncnn.bin \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/decoder_jit_trace-pnnx.ncnn.param \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/decoder_jit_trace-pnnx.ncnn.bin \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/joiner_jit_trace-pnnx.ncnn.param \
./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/joiner_jit_trac …
```

Fix modified beam search

---

sherpa-ncnn/csrc/conv-emformer-model.h

Replace the fixed value with a expression using the chunk length and right context length, such that the modification can be made as small as possible if one of the value changed

modify return value of function Segment

---

build-riscv64-linux-gnu.sh
toolchains/riscv64-linux-gnu.toolchain.cmake

You can find pre-compiled binaries at
https://huggingface.co/csukuangfj/sherpa-ncnn-pre-compiled-binaries/tree/main/riscv64
We use the board [VisionFive 2](https://www.starfivetech.com/en/site/boards) for testing.
We use the model
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#csukuangfj-sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16-bilingual-chinese-english
Note: It is a small model since the RTF of a larger model on this board is greater than 1.
Note: CPU is used for testing. No GPU is used during the test.
TO BE DONE.  I don't have a microphone at hand.

Support RISC-V

---

android/SherpaNcnn/app/src/main/java/com/k2fsa/sherpa/ncnn/MainActivity.kt

To match the example model used in the documentation:
https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html#download-pre-trained-models

Change default model type to match the documentation

---

.github/scripts/run-test.sh
c-api-examples/decode-file-c-api.c
sherpa-ncnn/c-api/c-api.cc
sherpa-ncnn/c-api/c-api.h
sherpa-ncnn/csrc/CMakeLists.txt
sherpa-ncnn/csrc/context-graph.cc
sherpa-ncnn/csrc/context-graph.h
sherpa-ncnn/csrc/decoder.h
sherpa-ncnn/csrc/hypothesis.h
sherpa-ncnn/csrc/modified-beam-search-decoder.cc
sherpa-ncnn/csrc/modified-beam-search-decoder.h
sherpa-ncnn/csrc/recognizer.cc
sherpa-ncnn/csrc/recognizer.h
sherpa-ncnn/csrc/sherpa-ncnn.cc
sherpa-ncnn/csrc/stream.cc
sherpa-ncnn/csrc/stream.h

support hotwords in C++, using bin/sherpa-ncnn to test

support hotwords in C++

---

CMakeLists.txt
android/SherpaNcnn/app/src/main/java/com/k2fsa/sherpa/ncnn/MainActivity.kt
android/SherpaNcnn/app/src/main/java/com/k2fsa/sherpa/ncnn/SherpaNcnn.kt
sherpa-ncnn/jni/jni.cc

Recreate the stream after restart.

Fix an Android bug.

---

CMakeLists.txt
sherpa-ncnn/csrc/features.cc
sherpa-ncnn/csrc/generate-int8-scale-table.cc

See also https://github.com/k2-fsa/sherpa-onnx/issues/514
Note that this PR is a bug-fix.

Use high_freq -400 in computing fbank features.

---

.github/workflows/build-wasm-simd.yaml
.github/workflows/go.yaml
.github/workflows/test-pip-install.yaml
CMakeLists.txt
build-wasm-simd.sh
sherpa-ncnn/c-api/c-api.h
wasm/CMakeLists.txt
wasm/app.js
wasm/assets/.gitignore
wasm/assets/README.md
wasm/index.html
wasm/sherpa-ncnn-wasm-main.cc
wasm/sherpa-ncnn.js

Expect to finish it this week.

Add WebAssembly

---

.github/workflows/wasm-simd-hf-space-en.yaml
.github/workflows/wasm-simd-hf-space-zh-en.yaml

You can find the two spaces at
https://www.modelscope.cn/studios/k2-fsa/web-assembly-asr-sherpa-ncnn-zh-en/summary
https://modelscope.cn/studios/k2-fsa/web-assembly-asr-sherpa-ncnn-en/summary

Publish wasm to model scope

---

.github/workflows/npm.yaml
CMakeLists.txt
nodejs-examples/package.json

To fix the following error
```
/home/runner/work/sherpa-ncnn/sherpa-ncnn/nodejs-examples/node_modules/sherpa-ncnn/sherpa-ncnn.js:199
this.Module.HEAPF32.set(samples, this.pointer / samples.BYTES_PER_ELEMENT);
^
TypeError: Cannot read properties of undefined (reading 'set')
at Stream.acceptWaveform (/home/runner/work/sherpa-ncnn/sherpa-ncnn/nodejs-examples/node_modules/sherpa-ncnn/sherpa-ncnn.js:199:25)
```
by fixing the version of emsdk.

Fix nodejs

---

nodejs-examples/package.json
nodejs-examples/real-time-speech-recognition-microphone-advanced-display.js

See also https://github.com/k2-fsa/sherpa-onnx/pull/1909
CC @wanghsinche

Update nodejs microphone example to use mic
